package main;
/*PRACTICA APLICACION DE GESTION DE ESCRITORIO:
  
 SIGUIENDO LOS CONCEPTOS Y EJEMPLOS MOSTRADOS CREAR UNA APP DE GESTION PARA UN
 NEGOCIO,EN LA CUAL SE GESTIONES INFORMACIONES SOBRE CLIENTES Y PRODUCTOS,
 EL PRODUCTO SERA EL DEL NEGOICIO A LEGIR POR EL PROGRAMADOR,
 DEBERA TENER AL MENOS 7 CAMPOS Y DEBERA ESTAR ALMACENADO EN UNA TABLA DE BASE DE DATOS.
 LA GESTION DEBERA PERMITIR REGISTRAR LISTAR EDITAR Y BORRAR INOFRMACIONES:
 SOLO SERA NECESARIO REGISTRAR 
 *OPCIONALES:
 USAR 3 CAMPO DE ENTRADA NO ENSEÑADA EN CLASE PARA EL PRODUCTO A LEGIR
 (PEJEM:CKECKBOX, LISTA DESPLEGABLE,RADIO BUTTONS )
 *INTENTAR REALIZAR UN LISTADO DE INFORMACIONES EN LOS PANELES DE LISTADO
 
 
 */
import ventanas.VentanaPrincipal;

public class Principal {

	public static void main(String[] args) {
		new VentanaPrincipal();
		

	}

}
